# Object Detection

In [1]:
# Importing necessary packages

import numpy as np
import argparse
import cv2
from easydict import EasyDict as edict
import matplotlib.pyplot as plt
from IPython.display import Image

In [2]:
# Defining a disctionary containing all the arguments to be passed

args_dict = edict({'image':'images/third.jpg' , 'prototxt':'MobileNetSSD_deploy.prototxt.txt',
                   'model':'MobileNetSSD_deploy.caffemodel', 'confidence':0.2})

In [3]:
args_dict['image']

'images/third.jpg'

In [4]:
# initialize the list of class labels MobileNet SSD was trained to detect

CLASSES = ["background", "aeroplane", "bicycle", "bird", "boat",
	"bottle", "bus", "car", "cat", "chair", "cow", "diningtable",
	"dog", "horse", "motorbike", "person", "pottedplant", "sheep",
	"sofa", "train", "tvmonitor"]

In [5]:
#generate a set of bounding box colors for each class

COLORS = np.random.uniform(0, 255, size=(len(CLASSES), 3))

In [6]:
COLORS.shape

(21, 3)

In [7]:
for i in range(len(COLORS)):
        print(COLORS[i])

[ 12.19326145 171.77501604 161.04489338]
[100.04124277 103.24125508  85.6762676 ]
[133.99325843 160.13380471   8.49715649]
[254.27942135 194.49589165  53.01844045]
[219.65793111 191.89528673 117.52494176]
[249.95263125 249.65028438 125.33539403]
[  2.41362362 100.78715025 184.96585665]
[111.32317303 108.59963769  37.37256411]
[145.61751425 219.79422026 171.65799698]
[240.44807349 133.75404676 124.23431531]
[184.60684019 202.57344253  99.14718517]
[ 1.56841428 14.13216944 68.48856817]
[ 20.08330813  46.06466946 100.64897311]
[ 35.14939847 157.93279964  27.94220581]
[109.46470997 123.34178613 151.15640426]
[244.69788092  25.13152477  89.81208873]
[162.19647225  44.82734    166.64249221]
[190.06659059  32.72263317 149.6230781 ]
[239.07754322 149.76406483 127.15625481]
[ 73.48607528   7.2356706  101.47913499]
[  9.06185938  58.83202942 217.49965383]


In [8]:
# load our serialized model from disk
print("[INFO] loading model...")
net = cv2.dnn.readNetFromCaffe(args_dict["prototxt"], args_dict["model"])

[INFO] loading model...


In [12]:
# load the input image and construct an input blob for the image
# by resizing to a fixed 300x300 pixels and then normalizing it
# (note: normalization is done via the authors of the MobileNet SSD
# implementation)
#print(f'shape of immported Image = {image.shape}')
image = cv2.imread(args_dict['image'])
#plt.figure(figsize=(100,100))
#plt.imshow(image)
#plt.show()

In [13]:
(h,w) = image.shape[0:2]

In [14]:
blob = cv2.dnn.blobFromImage(cv2.resize(image, (300, 300)), 0.007843, (300, 300), 127.5)

In [15]:
blob.shape

(1, 3, 300, 300)

In [16]:
# pass the blob through the network and obtain the detections and predictions

print("[INFO] computing object detections...")
net.setInput(blob)
detections = net.forward()

[INFO] computing object detections...


In [ ]:
for i in np.arange(0, detections.shape[2]):
    confidence = detections[0, 0, i, 2]
    if confidence > args_dict['confidence']:
        box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
        idx = int(detections[0, 0, i, 1])
        (startX, startY, endX, endY) = box.astype('int')
        cv2.rectangle(image, (startX, startY), (endX, endY), COLORS[idx], 2)
        
        #Label for predictions
        label = "{}: {:.2f}%".format(CLASSES[idx], confidence*100)
        y = startY - 15 if startY - 15 > 15 else startY + 15
        cv2.putText(image, label, (startX, y), cv2.FONT_HERSHEY_SIMPLEX, 0.5, COLORS[idx], 2)
        
        
cv2.imshow("Output", image)
cv2.waitKey(0)